Update action.yml

diff --git a/.github/workflows/build-process1/action.yml b/.github/workflows/build-process1/action.yml
--- a/.github/workflows/build-process1/action.yml
+++ b/.github/workflows/build-process1/action.yml
@@ -1,1 +1,349 @@
+name: 'Execute the compilation process.'
 
+runs:
+  using: 'composite'
+  steps:
+      - name: Added mkdtboimg to kernel (Experiment)
+        if: env.HAVE_NO_DTBO == 'true' && env.HAVE_NO_DTBO_TOOL != 'true'
+        shell: bash
+        run: |
+          # Get MKDTBO tool to kernel
+          cd $GITHUB_WORKSPACE/device_kernel/scripts/dtc
+          ${{ env.CURLX }} https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz src.tar.gz
+          tar zxvf src.tar.gz
+          rm -f src.tar.gz
+
+          # Hook dtbo generate code to kernel
+          cd $GITHUB_WORKSPACE/device_kernel
+          sed -i '/targets := Image Image.bz2 Image.gz Image.lz4 Image.lzma Image.lzo/s/$/ dtbo.img/' ./arch/"${{ env.KERNEL_ARCH }}"/boot/Makefile
+          sed -i '/# Add RTIC DTB to the DTB list if RTIC MPGen is enabled/i \DTBO_OBJS := $(shell find $(obj)/dts/ -name \\*.dtbo)\n' arch/"${{ env.KERNEL_ARCH }}"/boot/Makefile
+          sed -i '/$(obj)\/Image\.gz-dtb: $(obj)\/Image\.gz $(DTB_OBJS) FORCE/a \#DTBO\n$(obj)\/dtbo.img: $(DTBO_OBJS) FORCE\n\t$(call if_changed,mkdtimg)' ./arch/"${{ env.KERNEL_ARCH }}"/boot/Makefile
+          sed -i '/KBUILD_DTBS\t:= dtbs/a \#DTBO\nKBUILD_DTBO_IMG := dtbo.img' ./arch/"${{ env.KERNEL_ARCH }}"/Makefile
+          sed -i '/PHONY += vdso_install/i \ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)\n$(KBUILD_DTBO_IMG): dtbs\n\t$(Q)$(MAKE) $(build)=$(boot) $(boot)/$@\n\nall: $(KBUILD_DTBO_IMG)\nendif' arch/"${{ env.KERNEL_ARCH }}"/Makefile
+          sed -i '/dtc-tmp = $(subst $(comma),_,$(dot-target)\.dts\.tmp)/a \#DTBO\n# mkdtimg\n#----------------------------------------------------------------------------\nquiet_cmd_mkdtimg = DTBOIMG $@\ncmd_mkdtimg = python3 $(srctree)\/scripts\/dtc\/mkdtboimg.py create $@ --page_size=4096 $(filter-out FORCE,$^)' ./scripts/Makefile.lib
+
+      - name: Setup ccache
+        uses: hendrikmuhs/ccache-action@v1.2.22
+        with:
+          key: build-kernel-${{ env.DEVICE_NAME }}${{ env.UPLOADNAME }}
+          max-size: 2G
+
+      - name: Build Kernel
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+
+          # Function
+          BUILD_PROCESS(){
+          if [ -n "$1" ]; then
+            echo "Select: $1"
+            local BUILD_CLANG="$1"
+          else
+            BUILD_CLANG=""
+          fi
+
+          if [ -n "${{ env.CLANG_SOURCE }}" ]; then
+            export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH
+          fi
+
+          if [[ "$BUILD_CLANG" == "true" ]]; then
+            echo "========================"
+            echo "=Read Defconfig (Clang)="
+            echo "========================"
+            make CC="ccache clang" O=out ARCH="${{ env.KERNEL_ARCH }}" ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.DEFCONFIG_NAME }}
+          else
+            echo "================"
+            echo "=Read Defconfig="
+            echo "================"
+            make O=out ARCH="${{ env.KERNEL_ARCH }}" ${{ env.DEFCONFIG_NAME }}
+          fi
+
+          if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
+            echo "================="
+            echo "=Merge Config(s)="
+            echo "================="
+            IFS=',' read -ra MERGE_CONFIG_FILES <<< "${{ env.MERGE_CONFIG_FILES }}"
+            for FILES in "${MERGE_CONFIG_FILES[@]}"; do
+                ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/"${{ env.KERNEL_ARCH }}"/configs/$FILES
+            done
+            if [[ "$BUILD_CLANG" == "true" ]]; then
+                echo "==============================="
+                echo "=Execuate olddefconfig (Clang)="
+                echo "==============================="
+                make CC="ccache clang" O=out ARCH="${{ env.KERNEL_ARCH }}" ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} olddefconfig
+            else
+                echo "======================="
+                echo "=Execuate olddefconfig="
+                echo "======================="
+                make O=out ARCH="${{ env.KERNEL_ARCH }}" olddefconfig
+            fi
+          fi
+
+          if [[ "${{ env.DROIDSPACES_ENABLE }}"  == "true" ]]; then
+            echo "================="
+            echo "=  Droidspaces  ="
+            echo "================="
+            ./scripts/kconfig/merge_config.sh -O out/ -m out/.config arch/"${{ env.KERNEL_ARCH }}"/configs/droidspaces.config
+            if [[ "$BUILD_CLANG" == "true" ]]; then
+                echo "==============================="
+                echo "=Execuate olddefconfig (Clang)="
+                echo "==============================="
+                make CC="ccache clang" O=out ARCH="${{ env.KERNEL_ARCH }}" ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} olddefconfig
+            else
+                echo "======================="
+                echo "=Execuate olddefconfig="
+                echo "======================="
+                make O=out ARCH="${{ env.KERNEL_ARCH }}" olddefconfig
+            fi
+          fi
+
+          # KPM Detect
+          if [[ "${{ env.KPM_ENABLE }}" == "true" ]] && [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+            if grep -q "CONFIG_KALLSYMS_ALL=y" "out/.config"; then
+                sed -i 's/# CONFIG_KPM is not set/CONFIG_KPM=y/' out/.config
+                echo "[+] Enabled KPM."
+            else
+                echo "[-] Your didn't enabled KALLSYMS_ALL."
+            fi
+
+            if grep -q "CONFIG_KPM=y" "out/.config"; then
+                echo "[+] Detected KPM."
+            else
+                echo "[-] Could not detect KPM."
+            fi
+          fi
+
+          if [[ "$BUILD_CLANG" == "true" ]]; then
+            echo "======================"
+            echo "=Execuate Clang Build="
+            echo "======================"
+
+            if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" == "true" ]]; then
+                make -j$(nproc --all) CC="ccache clang" ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} O=out ARCH="${{ env.KERNEL_ARCH }}" security/selinux/
+                echo "[+] Pre-built SELinux done."
+            fi
+
+            make -j$(nproc --all) CC="ccache clang" ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} O=out ARCH="${{ env.KERNEL_ARCH }}" 2>&1|tee error.log
+          else
+            echo "===================="
+            echo "=Execuate GCC Build="
+            echo "===================="
+
+            if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" == "true" ]]; then
+                make -j$(nproc --all) O=out ARCH="${{ env.KERNEL_ARCH }}" security/selinux/
+                echo "[+] Pre-built SELinux done."
+            fi
+
+            make -j$(nproc --all) O=out ARCH="${{ env.KERNEL_ARCH }}" 2>&1|tee error.log
+          fi
+          }
+
+          # Core
+          if [ -n "${{ env.CLANG_SOURCE }}" ]; then
+            if [ -n "${{ env.GCC_64 }}" ] && [ -n "${{ env.GCC_32 }}" ]; then
+                echo "=================================="
+                echo "=Detected Clang and GCC 64 and 32="
+                echo "=================================="
+                export "${{ env.GCC_64 }}"
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS true
+            elif [ "${{ env.GNU_GCC }}" == "true" ]; then
+                echo "============================"
+                echo "=Detected Clang and GNU GCC="
+                echo "============================"
+                export "${{ env.GCC_64 }}"
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS true
+            elif [ -n "${{ env.GCC_64 }}" ]; then
+                echo "==========================="
+                echo "=Detected Clang and GCC 64="
+                echo "==========================="
+                export "${{ env.GCC_64 }}"
+                BUILD_PROCESS true
+            else
+                echo "====================="
+                echo "=Detected Only Clang="
+                echo "====================="
+                BUILD_PROCESS true
+            fi
+
+          elif [ "${{ env.KERNEL_ARCH }}" == "arm64" ]; then
+            if [ -n "${{ env.GCC_64 }}" ] && [ -n "${{ env.GCC_32 }}" ]; then
+                echo "=================================="
+                echo "=Detected ARM64 GCC 64 and GCC 32="
+                echo "=================================="
+                export "${{ env.GCC_64 }}"
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS
+            elif [ "${{ env.GNU_GCC }}" == "true" ]; then
+                echo "========================"
+                echo "=Detected ARM64 GNU GCC="
+                echo "========================"
+                export "${{ env.GCC_64 }}"
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS
+            elif [ -n "${{ env.GCC_64 }}" ]; then
+                echo "============================"
+                echo "=Detected ARM64 Only GCC 64="
+                echo "============================"
+                export "${{ env.GCC_64 }}"
+                BUILD_PROCESS
+            fi
+
+          elif [ "${{ env.KERNEL_ARCH }}" == "arm" ]; then
+            if [ "${{ env.GNU_GCC }}" == "true" ]; then
+                echo "======================"
+                echo "=Detected ARM GNU GCC="
+                echo "======================"
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS
+            elif [ -n "${{ env.GCC_32 }}" ]; then
+                echo "====================="
+                echo "=Detected ARM GCC 32="
+                echo "====================="
+                export "${{ env.GCC_32 }}"
+                BUILD_PROCESS
+            fi
+
+          else
+            echo "invaild kernel arch, stop."
+            false
+          fi
+
+      - name: Generate DTBO
+        if: env.HAVE_NO_DTBO == 'true' && env.HAVE_NO_DTBO_TOOL == 'true'
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel
+          mkdir dtbo_tool
+          cd dtbo_tool
+          ${{ env.CURLX }} https://android.googlesource.com/platform/system/libufdt/+archive/master/utils.tar.gz mkdtboimg.tar.gz
+          tar zxvf mkdtboimg.tar.gz
+          cd ../
+          if [ -d "$GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot/dts/vendor" ]; then
+            python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtbo
+          else
+            python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot/dts/${{ env.GENERATE_CHIP }}/*.dtbo
+          fi
+
+      - name: Analyze compile error
+        if: ${{ failure() && env.BUILD_DEBUGGER == 'true' }}
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+
+          cp /tmp/Bin/check_error.sh ./
+          cp /tmp/Bin/pack_error_files.sh ./
+
+          bash check_error.sh
+          bash pack_error_files.sh
+
+      - name: KPM Patcher (Experiment)
+        if: env.KPM_ENABLE == 'true' && env.KPM_INLINE == 'true' || env.KPM_KPATCH_NEXT == 'true'
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+          IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/"${{ env.KERNEL_ARCH }}"/boot"
+
+          if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
+              MODE="gz-dtb"
+          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
+              MODE="gz"
+          elif [[ -f "$IMAGE_DIR/Image" ]]; then
+              MODE="plain"
+          else
+              echo "No valid Image file found."
+              exit 1
+          fi
+
+          case "$MODE" in
+            gz-dtb)
+              if [ -f "include/linux/set_memory.h" ]; then
+                  if ls $IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}/*.dtb 1> /dev/null 2>&1; then
+                      DTB_PATH="dts"
+                  elif ls $IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtb 1> /dev/null 2>&1; then
+                      DTB_PATH="dts/vendor"
+                  else
+                      echo "Not found dts, abort."
+                      false
+                  fi
+
+                  rm -f "$IMAGE_DIR/Image.gz-dtb" "$IMAGE_DIR/Image.gz"
+
+                  if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                    cp patch "$IMAGE_DIR/"
+                  else
+                    cp kpimg-linux "$IMAGE_DIR/"
+                    cp kptools-linux "$IMAGE_DIR/"
+                  fi
+
+                  cd "$IMAGE_DIR/" || exit 1
+
+                  if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                    ./patch
+                  else
+                    ./kptools-linux -p -k kptools-linux -i Image -o oImage
+                  fi
+
+                  rm -f Image
+                  mv oImage Image
+                  gzip -c Image > Image.gz
+                  cat Image.gz $DTB_PATH/${{ env.GENERATE_CHIP }}/*.dtb > Image.gz-dtb
+                  echo "Hook Image successfully !"
+              else
+                  echo "Not supported for your kernel !"
+              fi
+              ;;
+            gz)
+              rm -f "$IMAGE_DIR/Image.gz"
+
+              if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                cp patch "$IMAGE_DIR/"
+              else
+                cp kpimg-linux "$IMAGE_DIR/"
+                cp kptools-linux "$IMAGE_DIR/"
+              fi
+
+              cd "$IMAGE_DIR/" || exit 1
+
+              if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                ./patch
+              else
+                ./kptools-linux -p -k kptools-linux -i Image -o oImage
+              fi
+
+              rm -f Image
+              mv oImage Image
+              gzip -c Image > Image.gz
+              echo "Hook Image successfully !"
+              ;;
+            plain)
+
+              if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                cp patch "$IMAGE_DIR/"
+              else
+                cp kpimg-linux "$IMAGE_DIR/"
+                cp kptools-linux "$IMAGE_DIR/"
+              fi
+
+              cd "$IMAGE_DIR/" || exit 1
+
+              if [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+                ./patch
+              else
+                ./kptools-linux -p -k kptools-linux -i Image -o oImage
+              fi
+
+              mv oImage Image
+              echo "Hook Image successfully !"
+              ;;
+          esac
+
+      - name: Upload Build Error Files
+        if: ${{ failure() && env.BUILD_DEBUGGER == 'true' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: compile_error_files
+          path: |
+            device_kernel/error.log
+            device_kernel/error_files.zip
