Add files via upload

diff --git a/.github/workflows/build-ready1/action.yml b/.github/workflows/build-ready1/action.yml
--- a/.github/workflows/build-ready1/action.yml
+++ b/.github/workflows/build-ready1/action.yml
@@ -164,4 +164,162 @@ runs:
             fi
 
             if [[ "${{ env.KERNELSU_METHOD }}" == "shell" ]]; then
-                curl -sSL "https://raw.githubusercontent.com/${KERNELSU_AUTHO
+                curl -sSL "https://raw.githubusercontent.com/${KERNELSU_AUTHOR}/${KERNELSU_NAME}/refs/heads/${KERNELSU_ORIGIN_BRANCH}/kernel/setup.sh" | bash -s "$KERNELSU_BRANCH"
+
+            elif [[ "${{ env.KERNELSU_METHOD }}" == "manual" ]]; then
+                git clone "https://github.com/$KERNELSU_AUTHOR/$KERNELSU_NAME.git" -b "$KERNELSU_BRANCH" "$KERNELSU_FOLDER"
+                ln -sf "../$KERNELSU_FOLDER/kernel" "drivers/kernelsu"
+                grep -q "kernelsu" "$GITHUB_WORKSPACE/device_kernel/drivers/Makefile" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> $GITHUB_WORKSPACE/device_kernel/drivers/Makefile
+                grep -q "source \"drivers/kernelsu/Kconfig\"" "$GITHUB_WORKSPACE/device_kernel/drivers/Kconfig" || sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" "${GITHUB_WORKSPACE}/device_kernel/drivers/Kconfig"
+                echo "KernelSU Settings done."
+
+            elif [[ "${{ env.KERNELSU_METHOD }}" == "only" ]]; then
+                git clone "https://github.com/$KERNELSU_AUTHOR/$KERNELSU_NAME.git" -b "$KERNELSU_BRANCH" "$KERNELSU_FOLDER"
+                ln -sf "../$KERNELSU_FOLDER/kernel" "drivers/kernelsu"
+
+            fi
+          }
+
+          KERNELSU_MANUAL(){
+            if [[ "${{ env.KERNELSU_SOURCE }}" == *Next* ]]; then
+                KERNELSU_FOLDER="KernelSU-Next"
+                echo "KERNELSU_NAME=$KERNELSU_FOLDER" >> $GITHUB_ENV
+
+            else
+                KERNELSU_FOLDER="KernelSU"
+                echo "KERNELSU_NAME=$KERNELSU_FOLDER" >> $GITHUB_ENV
+
+            fi
+
+            if [[ "${{ env.KERNELSU_METHOD }}" == "shell" ]]; then
+                curl -sSL "${{ env.KERNELSU_SOURCE }}" | bash -s "${{ env.KERNELSU_BRANCH }}"
+
+            elif [[ "${{ env.KERNELSU_METHOD }}" == "manual" ]]; then
+                git clone "${{ env.KERNELSU_SOURCE }}" -b "${{ env.KERNELSU_BRANCH }}" "$KERNELSU_FOLDER"
+                ln -sf "../$KERNELSU_FOLDER/kernel" "drivers/kernelsu"
+                grep -q "kernelsu" "$GITHUB_WORKSPACE/device_kernel/drivers/Makefile" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> $GITHUB_WORKSPACE/device_kernel/drivers/Makefile
+                grep -q "source \"drivers/kernelsu/Kconfig\"" "$GITHUB_WORKSPACE/device_kernel/drivers/Kconfig" || sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" "${GITHUB_WORKSPACE}/device_kernel/drivers/Kconfig"
+                echo "KernelSU Settings done."
+
+            elif [[ "${{ env.KERNELSU_METHOD }}" == "only" ]]; then
+                git clone "${{ env.KERNELSU_SOURCE }}" -b "${{ env.KERNELSU_BRANCH }}" "$KERNELSU_FOLDER"
+                ln -sf "../$KERNELSU_FOLDER/kernel" "drivers/kernelsu"
+
+            fi
+          }
+
+
+          # Core
+          if [[ ${{ env.KERNELSU_AUTO_GET }} == "true" ]]; then
+            KERNELSU_AUTO
+
+          else
+            KERNELSU_MANUAL
+
+          fi
+          echo "KERNELSU_METHOD=${{ env.KERNELSU_METHOD }}" >> $GITHUB_ENV
+
+      - name: KPM Function Support
+        if: env.KPM_ENABLE == 'true'
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel
+
+          ENABLE_KPM_CONFIGS(){
+
+            sed -n '/^config KALLSYMS_ALL/,/^[^ \t]/p' init/Kconfig | grep -q 'depends on.*DEBUG_KERNEL' && echo "CONFIG_DEBUG_KERNEL=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+            echo "CONFIG_KALLSYMS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+            echo "CONFIG_KALLSYMS_ALL=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+          }
+
+          GET_KPM_TOOLS(){
+
+            echo "[+] Detected set_memory."
+            echo "CONFIG_KPM=y" >> ./arch/"${{ env.KERNEL_ARCH }}"/configs/${{ env.DEFCONFIG_NAME }}
+            ${{ env.CURLX }} "${{ env.KPM_PATCH_SOURCE }}" patch
+
+            if [ -f "patch" ]; then
+                chmod a+x patch
+                echo "[+] Get KPM Tools successfully !"
+            else
+                echo "[-] Get KPM Tools failed !"
+                false
+            fi
+
+          }
+
+          GET_KPATCH_NEXT_TOOLS(){
+
+            REPO="KernelSU-Next/KPatch-Next"
+            ${{ env.CURLX }} "https://github.com/$REPO/releases/latest/download/kpimg-linux" kpimg-linux
+            ${{ env.CURLX }} "https://github.com/$REPO/releases/latest/download/kptools-linux" kptools-linux
+
+            if [ -f "kptools-linux" ]; then
+                chmod a+x kptools-linux
+                echo "[+] Get KPatch-Next Tools successfully !"
+            else
+                echo "[-] Get KPatch-Next Tools failed !"
+                false
+            fi
+
+          }
+
+          if [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]] && [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+            echo "[+] Detected SukiSU-Ultra and enabled KPM Inline."
+            ENABLE_KPM_CONFIGS
+
+            if [ -f "include/linux/set_memory.h" ]; then
+                GET_KPM_TOOLS
+
+            else
+                cp /tmp/Patches/Patch/set_memory_to_49_and_low.patch ./
+                patch -p1 < set_memory_to_49_and_low.patch || true
+                echo "[+] Patch set_memory successfully !"
+                echo "[-] If have patch error (.rej), manual fixed it."
+                GET_KPM_TOOLS
+
+            fi
+
+          elif [[ "${{ env.KERNELSU_SOURCE }}" != *SukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" != "sukisu" ]] && [[ "${{ env.KPM_INLINE }}" == "true" ]]; then
+            echo "[-] Your KernelSU Fork could not support KPM Inline!"
+            false
+
+          elif [[ "${{ env.KPM_KPATCH_NEXT }}" == "true" ]]; then
+            GET_KPATCH_NEXT_TOOLS
+
+          else
+            ENABLE_KPM_CONFIGS
+            echo "[+] Necessary configuration items have been enabled for the KPM feature."
+
+          fi
+
+      - name: Set KSU and SUSFS for DEFCONFIG
+        shell: bash
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel
+
+          # Neccssary
+          echo "CONFIG_KSU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+          # Fork
+          if [[ "${{ env.KERNELSU_SOURCE }}" == *rsuntk* ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *next* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "rsuntk" ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *ReSukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "resukisu" ]]; then
+            if [[ ${{ env.SUSFS_ENABLE }} != "true" ]]; then
+                echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+            fi
+          fi
+
+          if [[ "${{ env.KERNELSU_SOURCE }}" == *blackslashxx* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "xxksu" ]]; then
+            echo "CONFIG_KSU_KPROBES_KSUD=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+          fi
+
+          if [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *ReSukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "resukisu" ]]; then
+            if [[ "${{ env.SUSFS_ENABLE }}" != "true" ]]; then
+                echo "CONFIG_KSU_SUSFS=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+            elif [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
+                echo "CONFIG_KSU_SUSFS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+            fi
+          fi
